### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by kuhnchris** [SpiegelEiXXL-WGJ-Creations/WGJ64-DungeonCrawiching#5]
- [ ] UI sounds (Button click, Level Up, Open Inventory)
- [ ] Player sounds (Attack, Dying, Going down a floor, using an item, picking up an item, Missing an attack (Miss!))
- [ ] Item sounds (Glitch Gun firing, Glitch Gun fizzing, Potion drinking, sword swing, enemy killing)
- [ ] Monster sounds (Attacking, being killed, Moving)

**Comment by ViktorRKraus** [comment]
[sounds1.zip](https://github.com/SpiegelEiXXL-WGJ-Creations/WGJ64-DungeonCrawiching/files/2442725/sounds1.zip)

**Comment by ViktorRKraus** [comment]
[UI Sounds.zip](https://github.com/SpiegelEiXXL-WGJ-Creations/WGJ64-DungeonCrawiching/files/2443694/UI.Sounds.zip)
Hier sind die UI sounds, der sounds folder hat etwas chaotisch einige dinge drin

**Comment by ViktorRKraus** [comment]
[Hero.zip](https://github.com/SpiegelEiXXL-WGJ-Creations/WGJ64-DungeonCrawiching/files/2443790/Hero.zip)

hier die helden sounds, die miss sind auch schon im sound 1 ordner drin

**Comment by ViktorRKraus** [comment]
[Item sounds.zip](https://github.com/SpiegelEiXXL-WGJ-Creations/WGJ64-DungeonCrawiching/files/2444018/Item.sounds.zip)

**Comment by ViktorRKraus** [comment]
[monster.zip](https://github.com/SpiegelEiXXL-WGJ-Creations/WGJ64-DungeonCrawiching/files/2444103/monster.zip)

**Comment by ViktorRKraus** [comment]
[game over.zip](https://github.com/SpiegelEiXXL-WGJ-Creations/WGJ64-DungeonCrawiching/files/2444175/game.over.zip)

**Comment by ViktorRKraus** [comment]
https://drive.google.com/file/d/1BzIRVGIwIWHlKlyo5zhFpOioZUfG8LT2/view?usp=sharing
